### ISSUE TITLE
Cannot publish library

### ISSUE THREAD

**Issue by selfrefactor** [nestdotland/nest.land#337]
I haven't changed anything in `Rambda` library that much since the last time publishing did work. For the last 2 months, it simply stopped working:

```
Arguments:
  publish

Deno version:
  deno: 1.19.1
  v8: 9.9.115.7
  typescript: 4.5.2

Eggs version:
  0.3.10

Platform:
  x86_64-unknown-linux-gnu

2023-07-18T17:59:15.573Z [DEBUG]    Options: { check: true }
2023-07-18T17:59:15.575Z [DEBUG]    Raw config: {
  "$schema": "https://x.nest.land/eggs@0.3.10/src/schema.json",
  name: "rambda",
  entry: "./mod.ts",
  description: "Lightweight and faster alternative to Ramda with included TS definitions",
  homepage: "https://github.com/selfrefactor/rambda",
  version: "8.2.0",
  releaseType: "minor",
  unstable: false,
  unlisted: false,
  files: [ "rambda.js", "index.d.ts", "immutable.d.ts", "./README.md", "./src/**/*.js" ],
  ignore: [ "node_modules", "source", "files" ],
  checkFormat: false,
  checkTests: false,
  checkInstallation: false,
  check: true,
  yes: true
}
2023-07-18T17:59:15.577Z [DEBUG]    Ignore: {
  accepts: [],
  denies: [
    /^\.git[^/]*\/+(?:[^/]*(?:\/|$)+)*$/,
    /^(?:[^/]*(?:\/|$)+)*\.idea\/*$/,
    /^(?:[^/]*(?:\/|$)+)*[^/]*\.log\/*$/,
    /^(?:[^/]*(?:\/|$)+)*coverage\/*$/,
    /^(?:[^/]*(?:\/|$)+)*node_modules\/*$/,
    /^(?:[^/]*(?:\/|$)+)*commit\.js\/*$/,
    /^\.vscode\/+settings\.json\/*$/,
    /^(?:[^/]*(?:\/|$)+)*compare-size-output\.js\/*$/
  ],
  extends: []
}
2023-07-18T17:59:15.655Z [DEBUG]    Matched files: [
]
2023-07-18T17:59:15.672Z [DEBUG]    Config: {
  "$schema": "https://x.nest.land/eggs@0.3.10/src/schema.json",
  name: "rambda",
  entry: "./mod.ts",
  description: "Lightweight and faster alternative to Ramda with included TS definitions",
  homepage: "https://github.com/selfrefactor/rambda",
  version: "8.2.0",
  releaseType: "minor",
  unstable: false,
  unlisted: false,
  files: [ "rambda.js", "index.d.ts", "immutable.d.ts", "./README.md", "./src/**/*.js" ],
  ignore: [ "node_modules", "source", "files" ],
  checkFormat: false,
  checkTests: false,
  checkInstallation: false,
  check: true,
  yes: true
}
2023-07-18T17:59:16.894Z [INFO]     The resulting module is: 
        - name: "rambda",
        - version: "8.3.0",
        - description: "Lightweight and faster alternative to Ramda with included TS definitions",
        - repository: "https://github.com/selfrefactor/rambda",
        - unlisted: false,
        - stable: true,
        - upload: true,
        - latest: true,
        - entry: "/mod.ts"
2023-07-18T17:59:16.898Z [INFO]     Files to publish:
        - ./mod.ts  (0.000029MB)
        - ./rambda.js  (0.006315MB)
        - ./src/_internals/constants.js  (0.000067MB)
...
        - ./src/zipObj.js  (0.000283MB)
        - ./src/zipWith.js  (0.000251MB)
2023-07-18T18:00:25.438Z [CRITICAL] An unexpected error occurred: "Something broke when sending pieces... " "Error: Something broke when sending pieces... \n    at Command.publish [as fn] (https://arweave.net/t73xsFyqdCTu0FVEzt_psO9MbOFNaOV_rVmfjJoDCs0/src/commands/publish.ts:380:11)\n    at async Command.execute (https://arweave.net/b4K9toBc51LZoKzXnXVFaz9TZaQKTIWPCl45yxgU8sc/command/command.ts:1014:7)\n    at async Command.parse (https://arweave.net/b4K9toBc51LZoKzXnXVFaz9TZaQKTIWPCl45yxgU8sc/command/command.ts:928:16)\n    at async https://arweave.net/t73xsFyqdCTu0FVEzt_psO9MbOFNaOV_rVmfjJoDCs0/eggs.ts:74:23"
```

I did try with:
- manually change version and `eggs publish`
- eggs publish --release-type minor --yes

**Comment by mannubaveja007** [comment]
Looks like it's this community is dead though to check what tom has built but already dead let me listen to the podcast meanwhile
